plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - Polynomial_Addition.md
  - https://github.com/vrajpatel001/vrajpatel001/blob/main/README.md
theme: jekyll-theme-cayman